package longpipes;

import java.util.*;
/**
 * Creates a quote that tells the user the Details and Total cost of all Pipes
 * Ordered.
 * @author GrD-10
 * @version 2.2
 */
public class Quote extends javax.swing.JFrame {
    /**
     * This method initiates the frame then populates it and 
     * disables the ability of the user to resize the frame.
     * 
     * @param order An array list of all the pipe objects created by the user
     * from the UserInterface.
     */
    public Quote(ArrayList order) {
        initComponents();
        populate(order);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quoteTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quoteOrderText = new javax.swing.JTextArea();
        overallCostText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quoteTitle.setText("Quote");

        quoteOrderText.setColumns(20);
        quoteOrderText.setRows(5);
        jScrollPane1.setViewportView(quoteOrderText);

        overallCostText.setText("Overall Cost: £0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(overallCostText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quoteTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(quoteTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(overallCostText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel overallCostText;
    private javax.swing.JTextArea quoteOrderText;
    private javax.swing.JLabel quoteTitle;
    // End of variables declaration//GEN-END:variables
    /**
     * This method styles the title then stops the text box being 
     * editable by the user calls the methods to calculate the overall cost 
     * of the full order then displayed the details for each individual order 
     * specific details for the user to inspect all values rounded to two decimal places.
     * @param order List of pipe objects.
     */
    public void populate(ArrayList <Pipe>order){
        quoteTitle.setFont(quoteTitle.getFont().deriveFont(18f));
        quoteTitle.setHorizontalAlignment(quoteTitle.CENTER);
        quoteOrderText.setEditable(false);
        double overallCost = 0;
        quoteOrderText.setText("Order Breakdown\n\n");
        for(int i = 0; i < order.size(); i++){
           overallCost += order.get(i).totalCost();        
           quoteOrderText.setText(quoteOrderText.getText() + "Order #" + (i+1) + "\n");
           quoteOrderText.setText(quoteOrderText.getText() + order.get(i).getPipeDetails());
           quoteOrderText.setText(quoteOrderText.getText() + "Quantity: " + (int)order.get(i).getQuantity() + "\n");
           quoteOrderText.setText(quoteOrderText.getText() + "Total cost: £" + order.get(i).totalCost() + "\n");
           quoteOrderText.setText(quoteOrderText.getText() + "\n");
        }
        overallCost = (double) Math.round(overallCost * 100) / 100;
        overallCostText.setText("Overall cost: £" + overallCost + "\n");
        overallCostText.setFont(overallCostText.getFont().deriveFont(18f));
        overallCostText.setHorizontalAlignment(overallCostText.CENTER);
    }
}